# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentLogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_login',
        ),
    ]
