# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentLogin', '0004_student_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
