# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentLogin', '0005_auto_20170920_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='campus',
            field=models.CharField(choices=[('Ettimadai', 'Ettimadai'), ('Amritapuri', 'Amritapuri'), ('Banglore', 'Banglore')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
