# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentLogin', '0008_auto_20170921_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='branch',
            field=models.CharField(blank=True, choices=[('Btech_CSE', 'Btech_CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('Civil', 'Civil'), ('Chem', 'Chem'), ('EIE', 'EIE'), ('AeroSpace', 'AeroSpace'), ('Mtech_CSE', 'Mtech_CSE'), ('Control & Instrumentation Engineering', 'Control & Instrumentation Engineering'), ('Cyber Security Systems & Networks', 'Cyber Security Systems & Networks'), ('Power & Energy', 'Power & Energy'), ('Robotics & Automation', 'Robotics & Automation'), ('Thermal & Fluids', 'Thermal & Fluids'), ('VLSI Design', 'VLSI Design'), ('Wireless Networks & Applications', 'Wireless Networks & Applications'), ('Communication Engineering & Signal Processing', 'Communication Engineering & Signal Processing'), ('Computer Science & Engineering - Data Science', 'Computer Science & Engineering - Data Science'), ('Embedded Systems', 'Embedded Systems'), ('Power Electronics', 'Power Electronics'), ('Thermal Science & Energy Systems', 'Thermal Science & Energy Systems'), ('Automotive Engineering', 'Automotive Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Communication Engineering & Signal Processing', 'Communication Engineering & Signal Processing'), ('Computational Engineering & Networking', 'Computational Engineering & Networking'), ('Control & Instrumentation Engineering', 'Control & Instrumentation Engineering'), ('Cyber Security', 'Cyber Security'), ('Engineering Design', 'Engineering Design'), ('Manufacturing Engineering', 'Manufacturing Engineering'), ('Material Science', 'Material Science'), ('Remote Sensing & Wireless Sensor Networks', 'Remote Sensing & Wireless Sensor Networks'), ('Renewable Energy Technologies', 'Renewable Energy Technologies'), ('Structural & Construction Engineering', 'Structural & Construction Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='course',
            field=models.CharField(blank=True, choices=[('BTech', 'BTech'), ('MTech', 'MTech')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Not Interested', 'Not Interested'), ('Not Recommended', 'Not Recommended')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='job_Interest',
            field=models.CharField(blank=True, choices=[('IT sector', 'IT sector'), ('Core engg', 'Core engg'), ('others', 'others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='stay',
            field=models.CharField(blank=True, choices=[('Hosteler', 'Hosteler'), ('DayScholar', 'DayScholar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='tenth_board',
            field=models.CharField(blank=True, choices=[('state', 'state'), ('CBSE', 'CBSE'), ('ICSC', 'ICSC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='twelth_board',
            field=models.CharField(blank=True, choices=[('state', 'state'), ('CBSE', 'CBSE'), ('ICSC', 'ICSC')], max_length=50),
        ),
    ]
