# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
