# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20170925_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
