# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50)),
                ('comp_ctc', models.IntegerField(default=0)),
                ('comp_date', models.DateField(default=0)),
                ('eligibility', multiselectfield.db.fields.MultiSelectField(choices=[('BTech', 'BTech'), ('MTech', 'MTech')], max_length=11)),
                ('branch', multiselectfield.db.fields.MultiSelectField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('Civil', 'Civil'), ('Chem', 'Chem'), ('EIE', 'EIE'), ('AeroSpace', 'AeroSpace'), ('CSE', 'CSE'), ('Control & Instrumentation Engineering', 'Control & Instrumentation Engineering'), ('Cyber Security Systems & Networks', 'Cyber Security Systems & Networks'), ('Power & Energy', 'Power & Energy'), ('Robotics & Automation', 'Robotics & Automation'), ('Thermal & Fluids', 'Thermal & Fluids'), ('VLSI Design', 'VLSI Design'), ('Wireless Networks & Applications', 'Wireless Networks & Applications'), ('Communication Engineering & Signal Processing', 'Communication Engineering & Signal Processing'), ('Computer Science & Engineering - Data Science', 'Computer Science & Engineering - Data Science'), ('Embedded Systems', 'Embedded Systems'), ('Power Electronics', 'Power Electronics'), ('Thermal Science & Energy Systems', 'Thermal Science & Energy Systems'), ('Automotive Engineering', 'Automotive Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Communication Engineering & Signal Processing', 'Communication Engineering & Signal Processing'), ('Computational Engineering & Networking', 'Computational Engineering & Networking'), ('Control & Instrumentation Engineering', 'Control & Instrumentation Engineering'), ('Cyber Security', 'Cyber Security'), ('Engineering Design', 'Engineering Design'), ('Manufacturing Engineering', 'Manufacturing Engineering'), ('Material Science', 'Material Science'), ('Remote Sensing & Wireless Sensor Networks', 'Remote Sensing & Wireless Sensor Networks'), ('Renewable Energy Technologies', 'Renewable Energy Technologies'), ('Structural & Construction Engineering', 'Structural & Construction Engineering')], max_length=732)),
            ],
        ),
    ]
