# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 09:21
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cir', '0002_company_details_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='branch',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Btech_CSE', 'Btech_CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('Civil', 'Civil'), ('Chem', 'Chem'), ('EIE', 'EIE'), ('AeroSpace', 'AeroSpace'), ('Mtech_CSE', 'Mtech_CSE'), ('Control & Instrumentation Engineering', 'Control & Instrumentation Engineering'), ('Cyber Security Systems & Networks', 'Cyber Security Systems & Networks'), ('Power & Energy', 'Power & Energy'), ('Robotics & Automation', 'Robotics & Automation'), ('Thermal & Fluids', 'Thermal & Fluids'), ('VLSI Design', 'VLSI Design'), ('Wireless Networks & Applications', 'Wireless Networks & Applications'), ('Communication Engineering & Signal Processing', 'Communication Engineering & Signal Processing'), ('Computer Science & Engineering - Data Science', 'Computer Science & Engineering - Data Science'), ('Embedded Systems', 'Embedded Systems'), ('Power Electronics', 'Power Electronics'), ('Thermal Science & Energy Systems', 'Thermal Science & Energy Systems'), ('Automotive Engineering', 'Automotive Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Communication Engineering & Signal Processing', 'Communication Engineering & Signal Processing'), ('Computational Engineering & Networking', 'Computational Engineering & Networking'), ('Control & Instrumentation Engineering', 'Control & Instrumentation Engineering'), ('Cyber Security', 'Cyber Security'), ('Engineering Design', 'Engineering Design'), ('Manufacturing Engineering', 'Manufacturing Engineering'), ('Material Science', 'Material Science'), ('Remote Sensing & Wireless Sensor Networks', 'Remote Sensing & Wireless Sensor Networks'), ('Renewable Energy Technologies', 'Renewable Energy Technologies'), ('Structural & Construction Engineering', 'Structural & Construction Engineering')], max_length=744),
        ),
    ]
