# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cir', '0004_auto_20170804_1248'),
        ('cir', '0003_auto_20170806_0921'),
    ]

    operations = [
    ]
