# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cir', '0005_merge_20170806_0955'),
        ('cir', '0005_merge_20170807_1115'),
    ]

    operations = [
    ]
