# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cir', '0006_merge_20170808_1515'),
        ('cir', '0006_merge_20170808_1337'),
    ]

    operations = [
    ]
