# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cir', '0007_merge_20170809_1327'),
        ('cir', '0007_merge_20170809_1310'),
    ]

    operations = [
    ]
