# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cir', '0007_merge_20170809_1332'),
        ('cir', '0008_merge_20170814_1228'),
    ]

    operations = [
    ]
