# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cir', '0009_merge_20170814_1254'),
        ('cir', '0008_merge_20170814_1224'),
    ]

    operations = [
    ]
