# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cir', '0010_merge_20170814_1346'),
        ('cir', '0010_merge_20170814_1348'),
    ]

    operations = [
    ]
